# Generated by Django 5.0.2 on 2024-02-19 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('AreaId', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('TipoArea', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstatusReporte',
            fields=[
                ('EstatusReporteId', models.AutoField(primary_key=True, serialize=False)),
                ('Color', models.CharField(max_length=20)),
                ('DescripcionCorta', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('LicenciaId', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=200)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('Activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Privilegio',
            fields=[
                ('PrivilegioId', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Eliminar', models.BooleanField(default=True)),
                ('Agregar', models.BooleanField(default=True)),
                ('Editar', models.BooleanField(default=True)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('Activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('BitacoraId', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('NumeroEquipo', models.IntegerField()),
                ('Modelo', models.CharField(max_length=50)),
                ('Version', models.CharField(max_length=50)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('Activo', models.BooleanField(default=True)),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BitaApi.area')),
            ],
        ),
        migrations.CreateModel(
            name='RelBitacoraLicencia',
            fields=[
                ('RelId', models.AutoField(primary_key=True, serialize=False)),
                ('Activo', models.BooleanField(default=True)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('FechaActualizacion', models.DateTimeField(auto_now_add=True)),
                ('Bitacoras', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BitaApi.bitacora')),
                ('Licencias', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BitaApi.licencia')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('ReporteId', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=1000)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('Activo', models.BooleanField(default=True)),
                ('Bitacoras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BitaApi.bitacora')),
                ('EstatusReportes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BitaApi.estatusreporte')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('UsuarioId', models.AutoField(primary_key=True, serialize=False)),
                ('Usuario', models.CharField(max_length=30, unique=True)),
                ('Password', models.CharField(max_length=30)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellidos', models.CharField(max_length=100)),
                ('FCreacion', models.DateTimeField(auto_now_add=True)),
                ('Activo', models.BooleanField(default=True)),
                ('Privilegios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Privilegios', to='BitaApi.privilegio')),
            ],
        ),
    ]
